version: '3'
services:
  app:
    build:
      context: ./app
    ports:
      - "4000:4000"
    volumes:
      - ./app/:/app

  server:
    build:
      context: ./server
    ports:
      - "3000:8080"
    volumes:
      - ./server/:/go/src/hack-health-solution/server